apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - port: 21
    protocol: TCP
    name: ftps
  - port: 21000
    protocol: TCP
    name: ftps-data
  - port: 21001
    protocol: TCP
    name: ftps-data1
  - port: 21002
    protocol: TCP
    name: ftps-data2
  - port: 21003
    protocol: TCP
    name: ftps-data3
  - port: 21004
    protocol: TCP
    name: ftps-data4
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.114