apiVersion: 1
datasources:
- name: Grafana
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: true
  database: local_monitoring
  user: admin
  password: admin
- name: nginx
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: nginx
  user: admin
  password: admin
- name: phpmyadmin
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: phpmyadmin
  user: admin
  password: admin
- name: ftps
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: ftps
  user: admin
  password: admin
- name: wordpress
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: wordpress
  user: admin
  password: admin
- name: mysql
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: mysql
  user: admin
  password: admin
- name: influxdb
  type: influxdb
  url: http://influxdb.default.svc.cluster.local:8086
  access: proxy
  isDefault: false
  database: influxdb
  user: admin
  password: admin