apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps19
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 2100
          hostPort: 21000
        - containerPort: 21001
          hostPort: 21001
        - containerPort: 21002
          hostPort: 21002
        - containerPort: 21003
          hostPort: 21003
        - containerPort: 21004
          hostPort: 21004